### ISSUE TITLE
Question about the seg-token mask computation

### ISSUE THREAD

**Issue by saunair** [mbzuai-oryx/groundingLMM#16]
Hi Authors, 
Thanks for the code, and datasets!
I had a question about this line here:  ` mask = input_ids[:, 1:] == self.seg_token_idx` Why do we index from the first token? Shouldn't the output hidden states have a 1-1 mapping with the input_ids?

**Comment by hanoonaR** [comment]
Hi @saunair,

Thank you for reaching out and for your interest in our work.

Regarding your question about the [line](https://github.com/mbzuai-oryx/groundingLMM/blob/ba4f2b6b724273a0ae141a6783d28cf5e36ece72/model/GLaMM.py#L167C9-L167C9) `mask = input_ids[:, 1:] == self.seg_token_idx`: this implementation choice relates to the training of LLM, ie. Vicuna - causal (autoregressive) model in our case, where each token is predicted based on the preceding tokens. 

During training, the labels are typically shifted to the right ([example](https://github.com/mbzuai-oryx/groundingLMM/blob/ba4f2b6b724273a0ae141a6783d28cf5e36ece72/model/llava/model/language_model/llava_llama.py#L113C17-L113C17)) so that the model learns to predict the next token in the sequence. This shifting is reflected in how the model aligns its predictions with the input sequence. As a result, the output hidden states are offset compared to the input Ids by one position.

Therefore, when creating a mask, we essentially have to align the mask with these output hidden states. I hope this clarifies your question. Feel free to reach out with any further questions, thank you.
