### ISSUE TITLE
About GranD Pre-training Dataset

### ISSUE THREAD

**Issue by Shengcao-Cao** [mbzuai-oryx/groundingLMM#37]
Hello GLaMM Team,

Thank you very much for sharing this fascinating work!

It seems that you have been incrementally uploading the pre-training dataset, GranD, to https://huggingface.co/datasets/MBZUAI/GranD. Just a few clarification questions:

1. Does the whole dataset use all 11M images from SA-1B?
2. Any estimation when the upload will be completed?

Thanks,
Shengcao

**Comment by hanoonaR** [comment]
Hi @Shengcao-Cao,

Thanks a lot for reaching out and for your interest in our work!
Yes, our dataset will include all 11 million images from the SA-1B dataset. We plan to release 1-2 million images weekly. It's been challenging to get to this point dealing with limited resources, having to redo some of our annotations because of data loss, and improving our models. This has made things take a bit longer than expected. The [run-pipeline.sh](https://github.com/mbzuai-oryx/groundingLMM/blob/main/GranD/run_pipeline.sh) script shows how complex our models are, which explains the delay in releasing everything.

We have released all the code necessary for generating the dataset ([run-pipeline.sh](https://github.com/mbzuai-oryx/groundingLMM/blob/main/GranD/run_pipeline.sh)). If you have the resources available, we encourage you to explore and utilize this code. We will try to help with any reproduction efforts.

Sorry for the wait, and thanks again for your support!

**Comment by Shengcao-Cao** [comment]
HI @hanoonaR ,

Thank you very much for your reply! I totally understand the complexity in your data preparation. Sincerely appreciate your efforts in sharing this great work with the community.

Best,
Shengcao
