### ISSUE TITLE
the demo caption is very simple

### ISSUE THREAD

**Issue by trouble-maker007** [mbzuai-oryx/groundingLMM#38]
the demo caption is very simple, not like the detailed one in the paper, did you limit the output max length?

the caption result is quite simple
<img width="1580" alt="image" src="https://github.com/mbzuai-oryx/groundingLMM/assets/73164596/4811402f-581a-4db8-aabd-9e616aa02b2d">
<img width="1521" alt="image" src="https://github.com/mbzuai-oryx/groundingLMM/assets/73164596/092163e0-f160-455c-9d03-933c253dda03">

**Comment by hanoonaR** [comment]
This issue seems to be a duplicate of [Issue #25](https://github.com/mbzuai-oryx/groundingLMM/issues/25), which we've  reopened to continue the discussion. Let's consolidate our conversation there to keep everything organized. I'll be closing this one to avoid fragmentation. Thanks for understanding!
